version: "2"
services:
  node:
    image: "node:9"
    user: "node"
    working_dir: /home/joj/src
    environment:
      - NODE_ENV=dev
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - ./src:/home/joj/src
    expose:
      - "8081"
    command: "npm --prefix /home/joj/src/chapter-listings run test-dev"
