# https://github.com/nodejs/docker-node#create-a-dockerfile-in-your-nodejs-app-project
version: "2"
services:
  adt:
      image: "node:10.2.1-slim"
      user: "node"
      working_dir: /home/joj/src
      environment:
        - NODE_ENV=dev
        - NPM_CONFIG_LOGLEVEL=info
      volumes:
        - ./src:/home/joj/src
      command: "npm --prefix /home/joj/src/adt run build"
  
  chapter_listings:
    image: "node:10.2.1-slim"
    user: "node"
    working_dir: /home/joj/src
    environment:
      - NODE_ENV=dev
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
        - ./src:/home/joj/src
    command: "npm --prefix /home/joj/src/chapter-listings run test-dev"

  blockchain_tests:
      image: "node:10.2.1-slim"
      user: "node"
      working_dir: /home/joj/src
      environment:
        - NODE_ENV=dev
        - NPM_CONFIG_LOGLEVEL=info
      volumes:
        - ./src:/home/joj/src
      command: "npm --prefix /home/joj/src/blockchain run test-dev"

  # blockchain_peers:
  #     image: "node:10.2.1-slim"
  #     user: "node"
  #     working_dir: /home/joj/src
  #     environment:
  #       - NODE_ENV=dev
  #       - NPM_CONFIG_LOGLEVEL=info
  #     volumes:
  #       - ./src:/home/joj/src
  #     command: "npm --prefix /home/joj/src/blockchain run test-dev"

  # api:
  #     image: "node:9"
  #     user: "node"
  #     working_dir: /home/joj/src
  #     environment:
  #       - NODE_ENV=dev
  #       - NPM_CONFIG_LOGLEVEL=info
  #     volumes:
  #       - ./src:/home/joj/src
  #     ports:
  #       - "8181:8181"
  #     expose:
  #       - "8181"
  #     command: "npm --prefix /home/joj/src/ui start"
